name: publish_development

on:
  push:
    tags:
      - "**-alpha-**"
      - "**-beta-**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull the latest version
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: Auto Packaging
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}]

      - name: Upload to Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: WindDungeonHelper
          path: .release/*.zip

      - name: Send a message to Discord if meets a failure
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          status: ${{ job.status }}
        if: failure()
