name: ðŸ§ª Publish Test Version

on:
  push:
    tags:
      - '**alpha**'
      - '**beta**'

jobs:
  build:
    name: ðŸ“¦ Package
    runs-on: ubuntu-latest
    steps:
      - name: Pull the latest version
        uses: actions/checkout@v4
      - name: Auto Packaging
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.RELEASE_API_TOKEN_CURSEFORGE }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.RELEASE_API_TOKEN_WAGO }}
      - name: Upload to Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: WindDungeonHelper
          path: .release/*.zip
      - name: Send a message to Discord if meets a failure
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_GITHUB_ACTIONS }}
          status: ${{ job.status }}
        if: failure()
